### ISSUE TITLE
app crashes: account id is sometimes null in the whoami request.

### ISSUE THREAD

**Issue by jrwren** [jrwren/domasimu#4]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62dabd]

goroutine 1 [running]:
main.main()
        /home/jrwren/go/src/github.com/jrwren/domasimu/cmd/domasimu/main.go:51 +0x33d
exit status 2
```

**Comment by pleum** [comment]
I'm trying to figure out how did it happen.

**Comment by laurauzcategui** [comment]
If the info account is empty the key is set to be omitempty: https://github.com/dnsimple/dnsimple-go/blob/master/dnsimple/identity.go#L15

**Comment by laurauzcategui** [comment]
I can push a PR if you are ok with it 👍

**Comment by jrwren** [comment]
Yes please.

**Comment by laurauzcategui** [comment]
could you assigned to me ? @jrwren

**Comment by pleum** [comment]
Oh, i just found problem we need to use account token to make request for account data https://github.com/pleum/domasimu/commit/e2dd1ae75cdbf8b734b76a3f6c1b76f33e7961b8

**Comment by jrwren** [comment]
@laurauzcategui sure, I can. My advice though: don't worry about it for most GH projects unless the project has a defined workflow. Most of us are just interested in PRs.

edit: actually, I don't know how to assign it to you, but I still welcome PRs
