### ISSUE TITLE
load config file from XDG-spec locations

### ISSUE THREAD

**Issue by jrwren** [jrwren/domasimu#9]
reading from $HOME/.domasimurc works right now, but that file should really be in a location compatible with XDG spec.  Use $XDG_CONFIG_HOME or $HOME/.config/domasimu/config

**Comment by lukechampine** [comment]
I can tackle this. IIUC, I just need to modify the paths in `getCreds`, correct?

**Comment by jrwren** [comment]
I think so, yes. Please be sure it uses a sane path in Windows too.
